# data
dataset: fd_pair
data_root: /home/contlrn/zkl/Data/AQA/FineDiving/FINADiving_MTL_256s
label_path: /home/contlrn/zkl/Data/AQA/FineDiving/Annotations/fine-grained_annotation_aqa.pkl
train_split: /home/contlrn/zkl/Data/AQA/FineDiving/Annotations/train_split.pkl
test_split: /home/contlrn/zkl/Data/AQA/FineDiving/Annotations/test_split.pkl

frame_length: 96
resolution: 112

usingDD: True
dive_number_choosing: True

start_frame_idx: [0, 10, 20, 30, 40, 50, 60, 70, 80]

# dataloader
train_batch_size_per_gpu: 4
test_batch_size_per_gpu: 4
num_workers: 4

# model
model: core_aqa

backbone: i3d
backbone_args:
  pretrained_path: weights/model_rgb.pth

neck: avg
neck_args: null

head: core
head_args: 
  in_channel: 2049
  hidden_channel: 256
  depth: 5

score_range: 30
voter_number: 10

# training
optimizer: adam
base_lr: 0.0001
lr_factor: 1.0
weight_decay: 0.00001

scheduler: null

epoch: 100
gpus: [0, 1]
fix_bn: True

# loss
criterion: nll_mse
