
# data
dataset: fd
data_root: /home/contlrn/zkl/Data/AQA/FineDiving/FINADiving_MTL_256s
label_path: /home/contlrn/zkl/Data/AQA/FineDiving/Annotations/fine-grained_annotation_aqa.pkl
train_split: /home/contlrn/zkl/Data/AQA/FineDiving/Annotations/train_split.pkl
test_split: /home/contlrn/zkl/Data/AQA/FineDiving/Annotations/test_split.pkl

frame_length: 96
resolution: 112

usingDD: True
dive_number_choosing: True

start_frame_idx: [0, 10, 20, 30, 40, 50, 60, 70, 80]

# dataloader
train_batch_size_per_gpu: 16
test_batch_size_per_gpu: 16
num_workers: 4

std: 5

label_max: 104.5
label_min: 0.0

# model
model: musdl_aqa

backbone: i3d
backbone_args:
  pretrained_path: weights/model_rgb.pth
  

neck: avg
neck_args: null

head: musdl
head_args:
  num_judges: 1 # 1 for USDL, 7 for MUSDL

# training
optimizer: adam
base_lr: 0.0001
lr_factor: 1.0
weight_decay: 0.00001

scheduler: null

epoch: 100
gpus: [0, 1]
fix_bn: False

# loss
criterion: kld
