# data
dataset: fisv
data_root: /home/contlrn/zkl/Data/AQA/VST/fis-v/swintx_avg_fps25_clip32
train_split: /home/contlrn/zkl/Data/AQA/VST/fis-v/train.txt
test_split: /home/contlrn/zkl/Data/AQA/VST/fis-v/test.txt

clip_num: 68
class_idx: 1
score_type: Total_Score

# dataloader
train_batch_size_per_gpu: 32
test_batch_size_per_gpu: 1
num_workers: 4

std: 5

label_max: 25
label_min: 0.0
score_range: 25
norm_score: True

# model
model: musdl_aqa

backbone: null
backbone_args: null

neck: avg
neck_args: null

head: musdl
head_args:
  num_judges: 1 # 1 for USDL, 7 for MUSDL

# training
optimizer: adam
base_lr: 0.0001
lr_factor: 1.0
weight_decay: 0.0001
momentum: 0.8

scheduler: null

epoch: 100
gpus: [0, 1]
fix_bn: False

# loss
criterion: kld