# data
dataset: fisv_pair
data_root: /home/contlrn/zkl/Data/AQA/VST/RG/swintx_avg_fps25_clip32
train_split: /home/contlrn/zkl/Data/AQA/VST/RG/train.txt
test_split: /home/contlrn/zkl/Data/AQA/VST/RG/test.txt

clip_num: 68
test_clip_fixed: True
score_type: Total_Score

score_range: 25
voter_number: 10

# dataloader
train_batch_size_per_gpu: 4
test_batch_size_per_gpu: 1
num_workers: 4

# model
model: t2cr_aqa

backbone: null
backbone_args: null

neck: null
neck_args: null

head: t2cr
head_args: 
  thin_dim: 34 # half num of clips
  full_dim: 68 # num of clips

# training
optimizer: adam
base_lr: 0.0001
lr_factor: 1.0
weight_decay: 0.0001
momentum: 0.8

scheduler: null

epoch: 100
gpus: [0, 1]
fix_bn: False

# loss
criterion: t2cr_loss