# data
dataset: fisv
data_root: /home/contlrn/zkl/Data/AQA/VST/fis-v/swintx_avg_fps25_clip32
train_split: /home/contlrn/zkl/Data/AQA/VST/fis-v/train.txt
test_split: /home/contlrn/zkl/Data/AQA/VST/fis-v/test.txt

clip_num: 68
test_clip_fixed: True
score_type: Total_Score

# dataloader
train_batch_size_per_gpu: 32
test_batch_size_per_gpu: 1
num_workers: 4

# model
model: aqa

backbone: null
backbone_args: null

neck: null
neck_args: null

head: hgcn
head_args: 
  num_groups: 1
  num_clips: 68

# training
optimizer: adam
base_lr: 0.0001
lr_factor: 1.0
weight_decay: 0.0001
momentum: 0.8

scheduler: null

epoch: 100
gpus: [0, 1]
fix_bn: False

# loss
criterion: mse