# data
dataset: logo_pair
data_root: /home/contlrn/zkl/Data/AQA/LOGO/logo_feats
label_path: /home/contlrn/zkl/Data/AQA/LOGO/info/anno_dict.pkl
formation_path: /home/contlrn/zkl/Data/AQA/LOGO/info/formation_dict.pkl
train_split: /home/contlrn/zkl/Data/AQA/LOGO/info/train_split3.pkl
test_split: /home/contlrn/zkl/Data/AQA/LOGO/info/test_split3.pkl

voter_number: 10
score_range: 100

# dataloader
train_batch_size_per_gpu: 4
test_batch_size_per_gpu: 1
num_workers: 4

# model
model: t2cr_aqa

backbone: null
backbone_args: null

neck: null
neck_args: null

head: t2cr
head_args: 
  thin_dim: 24 # half num of clips
  full_dim: 48 # num of clips

# training
optimizer: adam
base_lr: 0.0001
lr_factor: 1.0
weight_decay: 0.0001
momentum: 0.8

scheduler: null

epoch: 100
gpus: [0, 1]
fix_bn: False

# loss
criterion: t2cr_loss