
# data
dataset: mtl_pair
data_root: /home/contlrn/zkl/Data/AQA/MTL-AQA/new
label_path: /home/contlrn/zkl/Data/AQA/MTL-AQA/info/augmented_final_annotations_dict.pkl
train_split: /home/contlrn/zkl/Data/AQA/MTL-AQA/info/train_split_0.pkl
test_split: /home/contlrn/zkl/Data/AQA/MTL-AQA/info/test_split_0.pkl

frame_length: 103
temporal_shift: [-3, 3]

score_range: 30
voter_number: 10

usingDD: True
dive_number_choosing: False

# dataloader
train_batch_size_per_gpu: 2
test_batch_size_per_gpu: 2
num_workers: 4

# model
model: core_aqa

backbone: i3d
backbone_args:
  pretrained_path: weights/model_rgb.pth

neck: avg
neck_args: null

head: core
head_args: 
  in_channel: 2049
  hidden_channel: 256
  depth: 5

# training
optimizer: adam
base_lr: 0.0001
lr_factor: 1.0
weight_decay: 0.00001

scheduler: null

epoch: 100
gpus: [0, 1]
fix_bn: True

# loss
criterion: nll_mse
