# data
dataset: rg
data_root: /home/contlrn/zkl/Data/AQA/VST/RG/swintx_avg_fps25_clip32
train_split: /home/contlrn/zkl/Data/AQA/VST/RG/train.txt
test_split: /home/contlrn/zkl/Data/AQA/VST/RG/test.txt

clip_num: 68
score_type: Total_Score

# dataloader
train_batch_size_per_gpu: 4
test_batch_size_per_gpu: 1
num_workers: 4

# model
model: aqa

backbone: null
backbone_args: null

neck: avg
neck_args: null

head: dae
head_args: null

# training
optimizer: adam
base_lr: 0.001
lr_factor: 1.0
weight_decay: 0.0001
momentum: 0.8

scheduler: null

epoch: 100
gpus: [0, 1]
fix_bn: False

# loss
criterion: mse